### ISSUE TITLE
Provide huesdk nativ lib source or at least statically linked

### ISSUE THREAD

**Issue by abierfert** [PhilipsHue/HueSDK#19] opened 2018-01-26 07:05 UTC
Currently the usability of huesdk.so is quite confined. E.g. it requires a very specific version of stdc++ which might be present on Ubuntu (until an update happens and things break) but makes it unusable on other Linux systems (even if they are x86_64).

A perfect solution would be to provide the source code so it can be compiled by the developers for the target systems.

If it is not possible to provide the source code (or until then) a statically linked version would help, so all dependent libraries are included.

**Comment by jhvdb87** [comment] 2018-02-28 19:59
Sorry for the late response, but I put this item on our backlog. Opensource the SDK is under discussion, but will not happen soon.

**Comment by mrwhy-orig** [comment] 2018-06-27 13:46
@jhvdb87 Should we add this one to the new repo? Anyway are there any updates on this?

**Comment by jhvdb87** [comment] 2018-06-27 13:51
Yes, there is an update. Our linux binaries are now statically linked against libstdc++. However this is not released yet. 
The timeline for the release is mentioned in this ticket:
https://github.com/PhilipsHue/HueSDK/issues/12

We will try to speed up releases in te future, this is why we are moving to the other repository where it is for us easier to release new features to the public rather than only internally for our app. :)

**Comment by mrcirillo** [comment] 2018-07-09 02:18
Would this linking issue be the cause of an "UnsatisfiedLinkError" for every SDK call from my Archlinux machine? I am successfully loading libhuesdk.so before any call.

**Comment by mrwhy-orig** [comment] 2018-07-09 07:16
@mrcirillo Yepp.

**Comment by mrwhy-orig** [comment] 2018-08-18 06:58
@jhvdb87 Do you have a more concrete release date yet? Thx!

**Comment by jhvdb87** [comment] 2018-10-02 19:55
Released on our new repo.

**Closed by jhvdb87** 2018-10-02 19:55 UTC
